version: "3.8" #check if there is a new docker compose version
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - phpmyadmin
    restart: always

  web:
#    image: php:8.2-apache #check the php version you need for your project
    build: webphp #this line tells docker to build the image from the Dockerfile in the current directory
    ports:
      - "80" #this line maps your pc port to the container port
    depends_on:
      - db #this line links this container to the db container
    volumes:
      - ./html:/var/www/html #this line maps the content of ./html in your pc to the /var/www/html of the container
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
#    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql"
    restart: always

  db:
    image: mysql:8.0.0 #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD: root_password #you can change the mysql root password here
      MYSQL_DATABASE: lamp_db #you can change the database name here
    volumes:
      - ./mysql_data:/var/lib/mysql #this line maps the content of ./mysql_data in your pc to the /var/lib/mysql of the container
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" #this line maps your pc port to the container port
    depends_on:
      - db #this line links this container to the db container
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M
    restart: always
