version: "3.8" #check if there is a new docker compose version
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - phpmyadmin
    restart: always

  web1: &web-service
#    image: php:8.2-apache #check the php version you need for your project
    build: webphp #this line tells docker to build the image from the Dockerfile in the current directory
    ports:
      - "80" #this line maps your pc port to the container port
    depends_on:
      - db #this line links this container to the db container
    volumes:
      - ./html:/var/www/html #this line maps the content of ./html in your pc to the /var/www/html of the container
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
#    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql"
    restart: always

  db:
    image: mysql:8.0.0 #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD: root_password #you can change the mysql root password here
      MYSQL_DATABASE: lamp_db #you can change the database name here
    volumes:
      - ./mysql_data:/var/lib/mysql #this line maps the content of ./mysql_data in your pc to the /var/lib/mysql of the container
      - ./db_scripts/mysql_master.cnf:/etc/mysql/my.cnf
      - ./db_scripts/create_replication_user.sql:/docker-entrypoint-initdb.d/create_replication_user.sql
      - ./db_scripts/mysql_no_ssl.cnf:/etc/mysql/conf.d/disable_ssl.cnf
      - ./db_scripts/healthcheck.sh:/healthcheck.sh
    restart: always
    command: --server-id=1
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_replica:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lamp_db
    volumes:
      - ./mysql_replica_data:/var/lib/mysql
      - ./db_scripts/mysql_replica.cnf:/etc/mysql/my.cnf
      - ./db_scripts/replica_entrypoint.sh:/docker-entrypoint-initdb.d/replica_entrypoint.sh
    depends_on:
      - db
    restart: always
    command: 
      - --server-id=2
      - --log-bin=mysql-bin
      - --binlog-format=ROW

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # ports:
      # - "8080:80" #this line maps your pc port to the container port
    depends_on:
      - db #this line links this container to the db container
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M
    restart: always

  db_backup:
    image: mysql:8.0.0
    volumes:
      - ./backups:/backups
      - ./db_scripts/backup.sh:/backup.sh
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      db:
        condition: service_healthy
    command: ["/bin/sh", "-c", "chmod +x /backup.sh && /backup.sh"]
    restart: always
